name: My workflow
on:
  workflow_dispatch:
  schedule:
    - cron: "00,30 * * * *"
jobs:
  run-my-policy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: gscho/setup-cloud-custodian@v1
    - run: custodian run -s out policy.yml
